/*SCRIPT DE INSTALAÇÃO DO BD ============================================= */
CREATE TABLE IF NOT EXISTS users  (
IDPESSOA INT AUTO_INCREMENT PRIMARY KEY,
MATRICULA INT,
EMPRESA INT,
NOME varchar(50),
NASCIMENTO DATE,
CPF VARCHAR(11),
SEXO varchar(1),
FOTO TINYBLOB,
EMAIL varchar(50),
ENDENREÇO varchar(50),
TELEFONE INT,
ADMISSÃO DATE,
NIVEL varchar(13),
LOGIN varchar(50),
SENHA varchar(50)
);